name: Docker Releaser Workflow

on:
  workflow_dispatch:
    inputs:
      release_version:
        type: string
        description: release version when building docker containers (example&#58; 2.0.0)
  # # push:
  #   branches:
  #     - main

jobs:
  build_aws_connector_docker_image:
    name: AWS Connector - Release docker images
    runs-on: ubuntu-latest
    needs:
      - tag_generator
    steps:        
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build AWS Connector docker image
      uses: docker/build-push-action@v2
      with:
        file: ci/ca.dockerfile
        build-args: |
          BASE_IMAGE=alpine:3.14
        tags: |
            ghcr.io/lamassuiot/lamassu-aws-connector:${{ github.event.inputs.release_version }}
            ghcr.io/lamassuiot/lamassu-aws-connector:latest
        push: true
